services:
  nginx:
    image: nginx:latest
    container_name: project_nginx
    volumes:
      - ./_docker/nginx/new.so-penaty.ru.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: project_db
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: so_penaty_db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    restart: always


  reverb:
    ports:
      - "8080:8080"
