services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: project_phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - "127.0.0.1:4001:80"
    depends_on:
      - db
    restart: unless-stopped
